version: '3.7'
services:
  bigstock-gateway:
    build: ../../../gateway/docker/
    restart: always 
    container_name: bigstock-gateway
    ports:
      - "11081:11081" 
    depends_on:
    #  - redis    
    #  - bstock-postgresql 
      - bigstock-auth  
    environment:
      SPRING_CONSUL_HOST: big_stock_consul
      SPRING_CONSUL_PORT: 8500  
      SPRING_DATASOURCE_URL: jdbc:postgresql://bstock-postgresql:5432/bstock
      SPRING_DATASOURCE_USERNAME: bstockuser
      SPRING_DATASOURCE_PASSWORD: postgresql   
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: rabbitmq
      JAVA_COMMAND_STR: -Xlog:gc+heap=trace:file=/opt/bigstock/logs/Xlog.log:time,uptimemillis,tid  -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -Dcatalina.home=/opt/bigstock -Xms1868M -Xmx1868M -Xss1M  -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m  -XX:MaxGCPauseMillis=10 -XX:InitiatingHeapOccupancyPercent=60 -XX:+UnlockExperimentalVMOptions -XX:MaxTenuringThreshold=10 -XX:G1NewSizePercent=3
      JAR_NAME: bigstock-gateway.jar
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 2g       
    networks:
      - big_stock_network      
  bigstock-auth:
    build: ../../../auth/docker/
    restart: always 
    container_name: bigstock-auth
    ports:
      - "10093:10093" 
    networks:
      - big_stock_network  
    environment:
      SPRING_CONSUL_HOST: big_stock_consul
      SPRING_CONSUL_PORT: 8500  
      SPRING_DATASOURCE_URL: jdbc:postgresql://bstock-postgresql:5432/bstock
      SPRING_DATASOURCE_USERNAME: bstockuser
      SPRING_DATASOURCE_PASSWORD: postgresql
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: rabbitmq      
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JAVA_COMMAND_STR: -Xlog:gc+heap=trace:file=/opt/bigstock/logs/Xlog.log:time,uptimemillis,tid  -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -Dcatalina.home=/opt/bigstock/ -Xms1024M -Xmx1024M -Xss256K  -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m  -XX:MaxGCPauseMillis=10 -XX:InitiatingHeapOccupancyPercent=60 -XX:+UnlockExperimentalVMOptions -XX:MaxTenuringThreshold=10 -XX:G1NewSizePercent=3
      JAR_NAME: bigstock-auth.jar 
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: a26404691@gmail.com
      SPRING_MAIL_PASSWORD: uynt zdgf suhj cjmi
      SPRING_MAIL_FROM: a26404691@gmail.com
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: smtp.gmail.com
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 2g    
  bigstock-biz:
    build: ../../../biz/docker/
    restart: always 
    container_name: bigstock-biz
    ports:
      - "18080:18080" 
    depends_on:
     # - redis  
     # - rabbitmq  
     # - bstock-postgresql  
      - bigstock-gateway
    environment:
      SPRING_CONSUL_HOST: big_stock_consul
      SPRING_CONSUL_PORT: 8500  
      SPRING_DATASOURCE_URL: jdbc:postgresql://bstock-postgresql:5432/bstock
      SPRING_DATASOURCE_USERNAME: bstockuser
      SPRING_DATASOURCE_PASSWORD: postgresql     
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: rabbitmq 
      JAVA_COMMAND_STR: -Xlog:gc+heap=trace:file=/opt/bigstock/logs/Xlog.log:time,uptimemillis,tid  -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -Dcatalina.home=/opt/bigstock -Xms1868M -Xmx1868M -Xss1M  -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m  -XX:MaxGCPauseMillis=10 -XX:InitiatingHeapOccupancyPercent=60 -XX:+UnlockExperimentalVMOptions -XX:MaxTenuringThreshold=10 -XX:G1NewSizePercent=3
      JAR_NAME: bigstock-biz.jar  
    networks:
      - big_stock_network  
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 2g     
  bigstock-schedule:
    build: ../../../schedule/docker/
    restart: always 
    container_name: bigstock-schedule
    ports:
      - "18081:18081" 
    shm_size: 2g
   # depends_on:
   #   - redis    
   #   - bstock-postgresql
    environment:
      SPRING_CONSUL_HOST: big_stock_consul
      SPRING_CONSUL_PORT: 8500  
      SPRING_DATASOURCE_URL: jdbc:postgresql://bstock-postgresql:5432/bstock
      SPRING_DATASOURCE_USERNAME: bstockuser
      SPRING_DATASOURCE_PASSWORD: postgresql     
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: rabbitmq  
      CHROME_DRIVER_LINUX_PATH: /usr/local/bin/chromedriver
      #CHROME_LINUX_PATH: /home/bigstock/chrome-driver/chromedriver-linux64/chrome-linux64/chrome
      #DISPLAY: ":99"
      #CHROME_BIN: /usr/bin/google-chrome
      JAVA_COMMAND_STR: -Xlog:gc+heap=trace:file=/opt/bigstock/logs/Xlog.log:time,uptimemillis,tid  -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -Dcatalina.home=/opt/bigstock -Xms1868M -Xmx1868M -Xss1M  -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m  -XX:MaxGCPauseMillis=10 -XX:InitiatingHeapOccupancyPercent=60 -XX:+UnlockExperimentalVMOptions -XX:MaxTenuringThreshold=10 -XX:G1NewSizePercent=3
      JAR_NAME: bigstock-schedule.jar  
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 2g       
    networks:
      - big_stock_network       
   # volumes:
   #   - ../../../schedule/chrome-driver/chromedriver-linux64/chromedriver-linux64/chromedriver:/home/bigstock/chrome-driver/chromedriver-linux64/chromedriver  
   #   - ../../../schedule/chrome-driver/chromedriver-linux64/chrome-linux64/:/home/bigstock/chrome-driver/chromedriver-linux64/chrome-linux64
networks:
  big_stock_network:
    external: true                